spring:
  application:
    name: Authorization-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/AuthX
    username: postgres
    password: 01032002ama
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  spring doc:
    swagger-ui:
      path:/swagger-ui.html

  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: google-client-id
            client-secret: google-client-secret